name: Java Server CI/CD Pipeline (GHCR)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # [QUAN TRỌNG] Phải cấp quyền để GitHub Actions được phép ghi đè Image lên Packages
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Checkout mã nguồn
        uses: actions/checkout@v3

      - name: 2. Đăng nhập vào GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Tự động có sẵn, không cần cài đặt!

      - name: 3. Build và đẩy Image lên GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Thay đổi địa chỉ lưu trữ thành ghcr.io. Tên user bắt buộc viết CHỮ THƯỜNG.
          tags: ghcr.io/nauqmn/java-server:latest

      - name: 4. Deploy lên Server qua SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            script: |
            # Di chuyển vào thư mục chứa file docker-compose.yml trên server
            cd /duong_dan_toi_thu_muc_chua_file_compose
            
            # Kéo bản Image mới nhất từ GitHub Packages về
            docker compose pull server-api
            
            # Khởi động lại hệ thống ngầm, nó sẽ tự động thay container cũ bằng bản mới
            docker compose up -d